application: normil-ordliste
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /static/flash
  static_dir: swfs

- url: .*
  script: dictionary_app.app
